<a href="https://colab.research.google.com/github/aaingyunii/230620_numpy_continued/blob/main/230620_numpy_01_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# $pip install numpy
import numpy as np

In [7]:
#@title 1차원 배열
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [5]:
np.array([range(4)])

array([[0, 1, 2, 3]])

In [6]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
#@title 벡터화 연산

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [11]:
a*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [15]:
a == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [16]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [18]:
(a >3) & (a <7)

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [21]:
#@title 2차원 배열

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr = np.arange(1,9).reshape(2,-1)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr, arr.ndim, arr.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 2,
 (2, 4))

In [25]:
#@title 3차원 배열

t = np.arange(24).reshape(2,3,-1)
t

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
t, t.ndim, t.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 3,
 (2, 3, 4))

In [28]:
#@title 배열 복사

v = t.view()
c = t.copy()
v,c

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [30]:
t[0][0] = 100
t,v,c # v는 얕은 복사, c는 깊은 복사이므로
# t의 값에 변화가 있다면 v는 따라서 변하지만, c는 변하지 않았다.

(array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[100, 100, 100, 100],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [33]:
#@title 배열의 인덱싱

# 1차원 배열 = 리스트의 인덱싱
a = np.arange(5)
print(a)
a[0],a[-1],a[3]

[0 1 2 3 4]


(0, 4, 3)

In [37]:
# 다차원 배열 -> [] -> ,를 통해서 축을 구분
b = np.arange(6).reshape(2,-1)
b, b.ndim, b.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [38]:
b[0,0]

0

In [39]:
b[0,0] = 100
b

array([[100,   1,   2],
       [  3,   4,   5]])

In [42]:
#@title 배열 슬라이싱

# 다차원 배열 슬라이싱 -> 파이썬 슬라이싱 + 축 (axis) ,를 같이 쓰면 된다
a = np.arange(8).reshape(2,-1)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
a[0], a[0, :]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [44]:
a[: ,1]

array([1, 5])

In [46]:
a[1,1:]

array([5, 6, 7])

In [47]:
a[1:3, 0:2]

array([[4, 5]])

In [52]:
#@title 배열 인덱싱 (불리언 배열, 정수 배열)
# 불리언 배열 인덱싱

a1 = np.arange(1,10,2)
a2 = np.arange(1,10)
a1, a2[ a2 % 2 != 0], a2[ : : 2]

(array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]), array([1, 3, 5, 7, 9]))

In [54]:
# 정수 배열 인덱싱

idx = np.arange(0,9,3)
idx , a2[idx]

(array([0, 3, 6]), array([1, 4, 7]))

In [56]:
import random

r= random.choices(range(len(a2)),k=20)
r, a2[r]  # 무작위 r 요소들의 값을 받아 a2에서 해당하는 인덱의 값을 반복 출력

([6, 0, 8, 2, 6, 0, 5, 2, 6, 0, 0, 2, 5, 8, 2, 2, 4, 4, 6, 7],
 array([7, 1, 9, 3, 7, 1, 6, 3, 7, 1, 1, 3, 6, 9, 3, 3, 5, 5, 7, 8]))

In [58]:
#@title 다차원 배열에서의 배열 인덱싱

a = np.arange(1,13).reshape(3,-1)
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 2,
 (3, 4))

In [59]:
a[:, [0 , 3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [60]:
a[:, [3,0]]

array([[ 4,  1],
       [ 8,  5],
       [12,  9]])

In [63]:
a[ : : -1, [3,0]]

array([[12,  9],
       [ 8,  5],
       [ 4,  1]])

In [65]:
a[ : ,[True,True, False, False]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [66]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [67]:
np.where(a % 2 == 0)  # 다차원 배열 -> 행별로 인덱스

(array([0, 0, 1, 1, 2, 2]), array([1, 3, 1, 3, 1, 3]))

In [68]:
arr = np.arange(1, 9)
np.where(arr % 2 == 0)

(array([1, 3, 5, 7]),)

# 배열의 생성과 변형

In [70]:
x = np.arange(1,4)
x

array([1, 2, 3])

In [73]:
x, x.ndim, x.shape, x.dtype

(array([1, 2, 3]), 1, (3,), dtype('int64'))

In [74]:
x = np.arange(1.0,4.0)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

In [75]:
x = np.arange(1.0,4)
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.]), 1, (3,), dtype('float64'))

#### [Numpy 사용할 때 유용하게 쓰이는 사이트]( https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)

https://sharegpt.com/c/YeSV33B

In [80]:
x = np.arange(1,4, dtype ="f")
x, x.ndim, x.shape, x.dtype

(array([1., 2., 3.], dtype=float32), 1, (3,), dtype('float32'))

In [81]:
np.inf # 1/0 같은 무한대가 나오는 상황 (에러가 안나고)

inf

In [82]:
np.nan # 0/0 같은, null이 낀 연산 -> 값이 나올 수 없는 연산

nan

In [83]:
#@title 배열 생성

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
x = np.zeros((3, 5, 1))
x

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [85]:
np.zeros_like(x)

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [86]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [87]:
np.ones_like(x)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [88]:
np.empty(5) # 값이 뭐가 나올지 모른다.

array([1., 1., 1., 1., 1.])

In [91]:
np.linspace(1,10,5) # 선형적으로 균등분배된 구간 (선형 구간)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [92]:
np.logspace(0.1, 10, 5)

array([1.25892541e+00, 3.75837404e+02, 1.12201845e+05, 3.34965439e+07,
       1.00000000e+10])

In [94]:
A = np.arange(1,7).reshape(2,-1)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [96]:
A.reshape(-1)   # -1 => 전체길이

array([1, 2, 3, 4, 5, 6])

In [97]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [98]:
x = np.arange(5)
x, x.shape

(array([0, 1, 2, 3, 4]), (5,))

In [99]:
x[:, np.newaxis], x[:, np.newaxis].shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

In [100]:
x[np.newaxis, :], x[np.newaxis, :].shape

(array([[0, 1, 2, 3, 4]]), (1, 5))

# 배열 연결

```python
concatenate
hstack (horizontal)
vstack (vertical)
dstack (depth)
stack
r_
c_
tile
```
> ChatGPT 활용, 도움

In [101]:
a = np.arange(1, 4)
b = np.arange(10, 13)
a, b

(array([1, 2, 3]), array([10, 11, 12]))

In [102]:
np.concatenate((a, b)) # axis=0

array([ 1,  2,  3, 10, 11, 12])

In [103]:
np.concatenate((a, b), axis=0)
# np.concatenate((a, b), axis=1) <- 1차원

array([ 1,  2,  3, 10, 11, 12])

In [104]:
# hstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.hstack((a, b)), np.hstack((a, b)).shape, np.concatenate((a, b), axis=1)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]),
 (2, 6),
 array([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]]))

In [105]:
# vstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.vstack((a, b)), np.vstack((a, b)).shape, np.concatenate((a, b), axis=0)

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 (4, 3),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [106]:
# dstack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.dstack((a, b)), np.dstack((a, b)).shape

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [107]:
# stack
a = np.ones((2, 3))
b = np.zeros_like(a)
a, b, np.stack((a, b)), np.stack((a, b)).shape  # axis=0

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [108]:
axis = 0
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=0

(array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [109]:
axis = 1
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=1

(array([[[1., 1., 1.],
         [0., 0., 0.]],
 
        [[1., 1., 1.],
         [0., 0., 0.]]]),
 (2, 2, 3))

In [110]:
axis = 2
np.stack((a, b), axis=axis), np.stack((a, b), axis=axis).shape  # axis=2

(array([[[1., 0.],
         [1., 0.],
         [1., 0.]],
 
        [[1., 0.],
         [1., 0.],
         [1., 0.]]]),
 (2, 3, 2))

In [111]:
a = np.arange(1, 4)
b = np.arange(4, 7)
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [112]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [114]:
np.tile(a, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [115]:
c = np.tile(a, (2, 2))
np.array_split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [116]:
np.split(c, 2)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [117]:
np.array_split(c, 2, axis=0)

[array([[1, 2, 3, 1, 2, 3]]), array([[1, 2, 3, 1, 2, 3]])]

In [118]:
np.array_split(c, 2, axis=1)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 3],
        [1, 2, 3]])]