<a href="https://colab.research.google.com/github/aaingyunii/230621/blob/main/230621_numpy_02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [15]:
x = np.arange(1,10001)
y = np.arange(10001,20001)
x,y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [16]:
#@title 벡터화 연산

In [6]:
z= x+y  # -> 벡터화 연산
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [7]:
x == y

array([False, False, False, ..., False, False, False])

In [8]:
(x == y) | (x < y)

array([ True,  True,  True, ...,  True,  True,  True])

In [9]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [10]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [11]:
10 ** a

array([   10,   100,  1000, 10000])

In [13]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

# 스칼라 / 벡터

In [18]:
x = np.arange(10)
x, x.ndim, x.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 1, (10,))

In [20]:
x * 100  # 100 -> x라는 배열의 모양에 맞춰서 변형 (브로드캐스팅)

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [23]:
x = np.arange(12).reshape(-1,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
x *100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅

In [25]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [28]:
x + 1, x - 100, x * 200, x / 10 #  x라는 배열의 모양에 맞춰서 변형 (브로드캐스팅)

(array([1, 2, 3, 4, 5]),
 array([-100,  -99,  -98,  -97,  -96]),
 array([  0, 200, 400, 600, 800]),
 array([0. , 0.1, 0.2, 0.3, 0.4]))

In [29]:
x = np.arange(15).reshape(5,-1)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [33]:
x + y # 에러, 차원이 달라서 불가

ValueError: ignored

In [36]:
y2 = y[:, np.newaxis] # 차원을 맞추기 위해 newaxis
y2, y2.shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

In [38]:
x + y2  # y2 -> 짧았음 -> 1열 -> 3열로 반복확장

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

# 차원 축소 연산

In [42]:
x = np.random.randint(0,10,4)
x

array([6, 3, 4, 1])

In [47]:
print(np.sum(x),x.sum())  # 합계
print(np.max(x),x.max())  # 최댓값
print(np.min(x),x.min())  # 최솟값
print(np.argmax(x),x.argmax())   # 최댓값의 인덱스를 구하는거
print(np.argmin(x),x.argmin())   # 최솟값의 인덱스를 구하는거
print(np.mean(x),x.mean())   # 평균
print(np.median(x))   # 중간값 -> 전체 개수가 짝수 : 중간에 위치한 값 두개의 평균값이 중간값.
print(np.all(x > 5), (x > 5).all())   # 모두 True인지
print(np.any(x > 5), (x > 5).any())   # 하나라도 True 인지

14 14
6 6
1 1
0 0
3 3
3.5 3.5
3.5
False False
True True


In [48]:
x = np.random.randint(0,100,6).reshape(2,-1)
x

array([[18, 76, 24],
       [31, 53, 12]])

In [51]:
print(x.sum(), x.sum(axis=None) ) # 축을 신경을 안쓴다.
print(x.sum(axis=0) )  # 같은 행을 합쳐주겠다. 열들간의 연산 - > 열모양
print(x.sum(axis=1) )  # 같은 열을 합쳐주겠다. 행들간의 연산 -> 행모양


214 214
[ 49 129  36]
[118  96]


In [52]:
x

array([[18, 76, 24],
       [31, 53, 12]])

In [54]:
np.sort(x), np.sort(x, axis=-1)   # axis = -1 -> ndim -1 차원, 가장 안쪽 자리

(array([[18, 24, 76],
        [12, 31, 53]]),
 array([[18, 24, 76],
        [12, 31, 53]]))

In [56]:
np.sort(x, axis = 0)  , np.sort(x, axis = 0)[:,::-1] # 행 기준으로 정렬

(array([[18, 53, 12],
        [31, 76, 24]]),
 array([[12, 53, 18],
        [24, 76, 31]]))

In [62]:
np.sort(x, axis=1), np.sort(x, axis=1)[::-1,:]

(array([[18, 24, 76],
        [12, 31, 53]]),
 array([[12, 31, 53],
        [18, 24, 76]]))

In [60]:
a.sort()
a

array([1, 2, 3, 4])

In [61]:
np.argsort(a)

array([0, 1, 2, 3])

# 기술 통계

In [64]:
x = np.random.randint(-100, 100, 30)
x

array([-100,  -67,  -69,   28,  -15,   78,    8,   57,  -88,  -10,   21,
        -95,  -43,  -87,    7,  -14,  -20,   -5,   85,  -88,   95,    4,
         57,  -16,  -34,   -5,  -98,   23,   77,  -58])

In [72]:
print(len(x))
print(np.mean(x) , x.mean())
print(np.var(x) ," / ", x.var())  # 분산
print(np.std(x) ," / ", x.std())  # 표준편차
# max min median 생략
print(np.percentile(x, 0)) # 최솟값
print(np.percentile(x, 25)) # 1사분위수
print(np.percentile(x, 50)) # 2사분위수
print(np.percentile(x, 75)) # 3사분위수
print(np.percentile(x, 100))  # 최댓값, 4사분위수

30
-12.4 -12.4
3352.106666666667  /  3352.106666666667
57.897380481906666  /  57.897380481906666
-100.0
-64.75
-12.0
22.5
95.0


# 난수 발생

In [73]:
np.random.seed(2023)

In [93]:
np.random.rand(5)

array([0.62349644, 0.78699145, 0.7861026 , 0.7237945 , 0.12976952])

In [94]:
# np.random.rand((2, 5)) # shape 직접 지정 안됨

TypeError: ignored

In [75]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.random.shuffle(x)
x

array([8, 1, 9, 2, 3, 0, 5, 6, 7, 4])

In [82]:
print(np.random.choice(5, 5, replace = False))  # 비복원추출
print(np.random.choice(5, 3, replace = False))

[0 1 4 3 2]
[2 1 0]


In [83]:
print(np.random.choice(5, 3, replace = True))   # 복원추출
print(np.random.choice(5, 10))

[3 1 2]
[3 1 3 4 3 1 4 0 2 2]


In [84]:
np.random.rand(10)

array([0.95292932, 0.55450583, 0.53138268, 0.26830694, 0.20333695,
       0.49730989, 0.13649596, 0.05847877, 0.40140807, 0.43704097])

In [86]:
np.random.randn(10), np.random.randn(10).shape    # rand 와 randn -> shape (배열의 모양) 사용 가능

(array([-0.20194735,  2.15061366, -0.55962836,  1.6194802 , -0.54498249,
        -0.46354364, -2.10846967,  1.92129592,  0.83141425, -1.13348183]),
 (10,))

In [87]:
# 기댓값 3, 표준편차 0.5
np.random.randn(10) * 0.5 + 3

array([2.9173504 , 2.95600814, 2.7900422 , 4.13322514, 2.81293583,
       3.04324237, 3.27930034, 3.27051813, 2.95252578, 3.1159565 ])

In [88]:
np.random.randint(1,10,100)

array([2, 4, 8, 8, 3, 3, 9, 7, 8, 7, 5, 6, 9, 4, 6, 8, 1, 1, 7, 6, 1, 9,
       9, 1, 9, 8, 7, 2, 9, 9, 5, 3, 9, 4, 9, 2, 3, 9, 1, 4, 6, 3, 4, 8,
       2, 9, 8, 8, 4, 9, 9, 3, 1, 5, 2, 7, 3, 9, 7, 5, 8, 3, 8, 6, 9, 2,
       2, 7, 3, 9, 7, 8, 6, 2, 6, 6, 8, 2, 6, 7, 6, 5, 9, 4, 6, 8, 2, 9,
       9, 4, 5, 1, 2, 5, 7, 6, 8, 9, 2, 8])

In [89]:
r = np.random.randint(1,10,100)
r

array([4, 3, 3, 9, 3, 5, 3, 3, 3, 9, 1, 4, 8, 1, 7, 8, 7, 8, 9, 2, 4, 6,
       6, 3, 3, 7, 5, 7, 8, 7, 5, 5, 2, 1, 3, 1, 2, 4, 4, 3, 4, 1, 8, 4,
       1, 5, 7, 3, 6, 6, 9, 4, 5, 9, 5, 5, 8, 3, 4, 4, 4, 3, 7, 6, 6, 2,
       1, 5, 6, 6, 2, 7, 7, 8, 4, 4, 7, 8, 4, 5, 3, 2, 9, 5, 1, 6, 8, 3,
       7, 7, 7, 6, 2, 7, 5, 2, 1, 3, 5, 9])

In [90]:
np.unique(r)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.unique(r, return_counts = True)
# 첫번째 array는 고유값들
# 두번째 array는 고유값마다 몇개씩 있는지

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 9,  8, 16, 14, 13, 10, 14,  9,  7]))

In [95]:
index, value = np.unique(r, return_counts=True)
index, value

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 9,  8, 16, 14, 13, 10, 14,  9,  7]))

In [96]:
zip(index, value)

In [97]:
dict(zip(index, value))

{1: 9, 2: 8, 3: 16, 4: 14, 5: 13, 6: 10, 7: 14, 8: 9, 9: 7}